version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: jksantos/golang
    container_name: app
    restart: unless-stopped
    working_dir: /home/${USER}/go
    volumes:
      - ../:/home/jksantos/go
      - /home/${USER}/.ssh:/home/${USER}/.ssh:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
