version: "3.7"
services:
  app:
    build:
      args:
        user: vscode
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: jksantos/golang
    container_name: app
    restart: unless-stopped
    working_dir: /home/vscode/go
    volumes:
      - ../:/home/vscode/go
      - /home/${USER}/.ssh:/home/vscode/.ssh:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
